---
- name: reload_systemd
  systemd:
    daemon_reload: yes

- name: start_firewall
  systemd:
    name: firewall
    daemon_reload: yes
    enabled: true
    state:
      started
  notify:
    reload_systemd
